version: '3'

volumes:
  pg_data_production:
  static:
  media:

services:
  db:
    container_name: postgre_db_prod_foodgram
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    container_name: backend_prod
    image: onedocforall/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    container_name: frontend_prod
    image: onedocforall/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend
  gateway:
    container_name: nginx_prod
    image: onedocforall/foodgram_nginx
    env_file: .env
    volumes:
      - static:/static/
      - media:/app/media
      - ./docs/:/usr/share/nginx/html/api/docs/
      #- ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
    ports:
      - 9001:80
    depends_on:
      - backend
      - frontend