version: '3'

volumes:
  pg_data_production:
  backend_static:
  frontend_static:
  media:

services:
  db:
    container_name: postgre_db_prod_foodgram
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    container_name: backend_prod
    image: onedocforall/foodgram_backend
    env_file: .env
    volumes:
      - backend_static:/app/static/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    container_name: frontend_prod
    image: onedocforall/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - frontend_static:/frontend_static
    depends_on:
      - backend
  gateway:
    container_name: nginx_prod
    image: onedocforall/foodgram_nginx
    env_file: .env
    volumes:
      - backend_static:/static/backend/
      - frontend_static:/static/frontend/
      - media:/media
    ports:
      - 9001:80
    depends_on:
      - backend
      - frontend