version: '3'

volumes:
  pg_data_production:
  backend_static:
  frontend_static:
  media:

services:
  db:
    container_name: postgre_db_prod_foodgram
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    container_name: backend_prod
    image: onedocforall/foodgram_backend
    env_file: .env
    volumes:
      - backend_static:/app/static/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    container_name: frontend_prod
    image: onedocforall/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  gateway:
    container_name: nginx_prod
    image: onedocforall/foodgram_nginx
    env_file: .env
    volumes:
      - backend_static:/static/backend/
      - media:/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
    ports:
      - 9001:80
    depends_on:
      - backend
      - frontend