# Generated by Django 4.2.15 on 2024-10-09 12:16

import colorfield.fields
import django.core.validators
from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkMapped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_hash', models.CharField(default=recipes.models.generate_hash, max_length=10, unique=True)),
                ('original_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=7, samples=None, unique=True, validators=[django.core.validators.RegexValidator(message='Некорректный формат', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Цвет'),
        ),
    ]
